name: Start preview app

on:
  pull_request:
    branches:
      - main
    types: [ labeled, synchronize, opened, reopened, closed ]

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  preview-app:
    if: contains(github.event.pull_request.labels.*.name, 'PR preview app')
    name: Preview app
    environment:
      name: webserver-flowerwork-develop
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
      - name: Deploy preview app
        uses: superfly/fly-pr-review-apps@1.2.0
        id: deploy
        with:
          config: webserver/fly-develop.toml
          postgres: pg-fly-pr-staging
          region: waw
          org: FlowerWork
          app: webserver-flowerwork-develop

