name: Start preview app

on:
  pull_request:
    branches:
      - main
    types: [labeled, synchronize, opened, reopened, closed]

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  preview-app:
    if: contains(github.event.pull_request.labels.*.name, 'PR preview app')
    runs-on: ubuntu-latest
    name: Preview app
    environment:
      name: webserver-flowerwork-develop
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy preview app
        uses: superfly/flyctl-actions/setup-flyctl@master
        run: flyctl deploy --app webserver-flowerwork-develop --remote-only
        id: deploy
        with:
          config: webserver/fly-develop.toml
          postgres: pg-fly-pr-staging  # ← Added
          region: waw
          org: FlowerWork
          dockerfile: webserver/Dockerfile
